# Build settings
include: ["_pages"]
markdown: kramdown

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

theme: jekyll-theme-minimal
title: Indiana University Network Science Institute
description: Project Documentation

logo: "assets/favicon-194x194.png" # path of site logo, e.g. "/assets/images/logo.png"

#---
#  defaults:
#    # _docs
#    - scope:
#        path: ""
#        type: main
#      values:
#        sidebar:
#          nav: "main"
#  ---   

#include:
#  - _pages
  
collections:
  pages:
    output: true
    permalink: /:path/

baseurl: '/test1'

header_pages:
  - _pages/add-a-new-page.md
  - _pages/configure-the-guide.md

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  internal: true
  url: ./
- text: Add a new page
  internal: true
  url: add-a-new-page
- text: Configure the Guide
  internal: true
  url: configure-the-guide
- text: GitHub Setup
  internal: true
  url: github
